### ISSUE TITLE
Error on refreshing token

### ISSUE THREAD

**Issue by dJos1991** [michaelarnauts/repository.vtm.go#2]
Today I cannot open anything from VTM GO on Kodi. There is always a error pop-up.
Everything was working fine yesterday, but the token seems to be expired, as I can see in the logs, and there is a error when he is trying to renew the token.

Other add-ons are working fine, and I rebooted the system already, here are the logs (I removed the token ID on the second row :) ):

```
2022-05-31 19:56:43.066 T:1853    DEBUG <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is NOT valid: Signature has expired
2022-05-31 19:56:43.066 T:1853    DEBUG <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh: {'lfvpToken': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-plVdahmQ'}
2022-05-31 19:56:43.068 T:1853    DEBUG <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Starting new HTTPS connection (1): lfvp-api.dpgmedia.net:443
2022-05-31 19:56:43.285 T:1853    DEBUG <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "POST /vtmgo/tokens/refresh HTTP/1.1" 426 0
2022-05-31 19:56:43.286 T:1853    DEBUG <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=426): 
2022-05-31 19:56:43.288 T:1853    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 179, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 22, in index
                                                       if auth.get_tokens():
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 145, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh', data={
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 70, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 177, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh
                                                   -->End of Python script error report<--
                                                   
2022-05-31 19:56:43.288 T:1853    DEBUG <general>: onExecutionDone(33, /storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py)

```

**Comment by peno64** [comment]
I have exactly the same error with the same logs in kodi.log

**Comment by M0nty99** [comment]
I'm also having the same problem

**Comment by dJos1991** [comment]
There is already a fix, on the main vtm go addd-on repo :)
#https://github.com/add-ons/plugin.video.vtm.go/issues/324#issuecomment-1144001000
